spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Mihenk?currentSchema=public
    username: postgres
    password: 1118

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  messages:
    basename: messages
    encoding: UTF-8
